### PR TITLE
Use timeout for opening a connection

### PR DESCRIPTION
**Pull request by glindste**
If opening a connection to a server which does not respond and the default timeout is None, the socket would wait forever. With this change we use the timeout value given for method calls for establishing the connection as well. If a timeout is not defined None is passed, which will make it wait forever.

### CODE REVIEW

**Comment by glindste** [comment]
Sorry, forgot to run the test suite on the previous commit. The tests have been modified now for the new behaviour.

**Comment by ikuyamada** [comment]
Thank you for your contribution.
I think setting `timeout=None` and leaving the argument unspecified are not equivalent because the argument has the default value `_GLOBAL_DEFAULT_TIMEOUT`.

See: http://svn.python.org/projects/stackless/trunk/Lib/socket.py

In order not to override the default value, we might need to separately retrieve the default timeout by calling `getdefaulttimeout()` and use it as the default value of the timeout argument.

**Comment by ikuyamada** [comment]
@glindste What do you think about the above comment? I am sorry, but I will close this pr soon if you do not reply.

**Comment by glindste** [comment]
@ikuyamada I'm sorry I've been a bit busy lately. You're right, it should use the default timeout if the timeout value is `None`. I'll start working on a commit.

**Comment by glindste** [comment]
The latest commit should now use the global default timeout when no timeout is specified, instead of `None`.

**Comment by ikuyamada** [comment]
@glindste Thank you!

**Comment by ikuyamada** [comment]
I've just uploaded a new version v0.1.8 that includes this PR

**Comment by glindste** [comment]
@ikuyamada Alright, thank you!

**Pull request merged**
