### PR TITLE
add support for msgpack 2.0 binary type

### PR DESCRIPTION
**Pull request by hendrik-cliqz**
This PR adds the possibility to send binary data (as defined in msgpack 2.0). 

Without it binary content is send as string which fails during unpack because the client tries to decode it (using utf-8).

As client and server are provided it might be even better to enable this per default.

### CODE REVIEW

**Comment by hendrik-cliqz** [comment]
Hi, I can resolve the merge conflict if the feature itself is wanted, just let me know.

**Comment by ikuyamada** [comment]
Thanks :)
I am actually wondering that the proposed feature can cause a compatibility problem with other *MessagePack RPC* clients or servers in other languages since I think the *binary string* is not supported (and not required) in other languages.
This library aims to provide an alternative, gevent-compatible implementation of *MessagePack RPC*.

**Comment by hendrik-cliqz** [comment]
That's why I made it optional. Actually I do not know whether there are other clients. I also do not know how new the binary type aka msgpack 2.0 is. So if backwards-compatibility is important or not. But as said, in this PR this option is optional.

In my application I have the problem that the binary data I send from the server breaks in the client because the client tries to decode it using utf-8. I can change the encoding, but than my real strings are not properly decoded. The problem is that msgpack 1.0 can not distinguish between string and binary data, they are treated the same.

**Comment by ikuyamada** [comment]
I am sorry for replying so late.
I reconsider this PR and I now think that optionally supporting *use_bin_type* feature might be a good idea.
But the certain problem here is that the argument *use_bin_type* was introduced from msgpack-python 0.4.0. So using with older msgpack-python library, the proposed change causes a problem because the constructor of *Packer* class doesn't have the argument.

**Pull request closed without merging**
