### PR TITLE
fix compatibility with python3.7

### PR DESCRIPTION
**Pull request by moreorem**
changed client.c and server.c the parameters  exc_ + [type/value/traceback] to curexc_ [type/value/traceback]

### CODE REVIEW

**Comment by ikuyamada** [comment]
Thank you for your PR! However, the .c files should be automatically generated using cythonize.sh.
Would you please describe the problem that you need to address?

**Comment by moreorem** [comment]
Hello! I see... The problem I encountered was when trying to install through pip for python 3.7 version or when trying to compile from source code, the compiler wouldn't understand the exc_type, exc_value and exc_traceback names that reside in client.c and server.c files. It suggested replace with curexc_type, curexc_value and curexc_traceback names.

**Comment by ikuyamada** [comment]
Thanks. It seems that it is required to regenerate c files using newer version of Cython to support Python 3.7. I am going to work on it and release a new version soon.

**Comment by ikuyamada** [comment]
v0.1.17 has just released with regenerated c files. Thanks!

**Pull request closed without merging**
