### PR TITLE
Allow specification of logging path, and don't use the anonymous logging calls.

### PR DESCRIPTION
**Pull request by fake-name**
This is a minor change that allows the logging path to be overridden, and no longer uses the `logging.<level>()` calls. This was primarily done because calling the `logging.<level>()` calls can cause the logging library to sometimes install the `logging.basicConfig()` log handler, which leads to duplicate logging if another log-handler is installed.

### CODE REVIEW

**Comment by ikuyamada** [comment]
Thank you for your contribution!
However, a named logger can be configured from the user code (e.g., logging.getLogger('MpRPC').addHandler(handler)), I think it is unnecessary to add the *log_path* to the arguments of the RPCClient class.

**Comment by fake-name** [comment]
The problem is I already have a log handler, and yet somehow calling the `logging.info()`, `logging.debug()`, `logging.exception()` calls seems to trigger the installation of the `logging.basicConfig()` log handler, which then causes all my logging output to be duplicated by the two handlers.

Sure, I *could* go and manually detach the second log handler, but that's messy and brittle. I've done that before, but I'd rather not have to spend time futzing with the internals of the logging system state. It's much nicer to just never attach that spurious logger at all.

The exposing of the log path to the end-user isn't something I'm set on, much. Mostly, I just want to have *a* log path, rather then none at all (which is what is there before this PR).

**Comment by ikuyamada** [comment]
Thank you for your reply!
The current RPCClient directly calls the global logging module (e.g., logging.info()) and I totally agree that it is a bad practice. To address this, I would like to add a global *mprpc* logger in __init__.py in the next commit. Note that, the logger can be configured from a user code such as adding FileHandler(), so the user can specify arbitrary log path.

**Comment by fake-name** [comment]
That would address the crux of the issue, though I still would like to be able to set the path. I use a lot of libraries, and it's very convenient to be able to not have to add custom logging handlers for every library that does it's own internal logging.

Also, being able to configure the log-path on a per *instance* basis means you can have multiple instances with different log paths, which I can see being of value in some cases.

**Comment by ikuyamada** [comment]
Thank you for your comment.
I somewhat agree with your opinion, but I also think that this feature is somewhat specific.
I am sorry but as a maintainer of this library, I would like to maintain the simplicity.

**Pull request closed without merging**
